#!/bin/bash

# Less syntax highlighting
# first, execute 'brew install source-highlight'
export LESSOPEN='| /usr/local/bin/src-hilite-lesspipe.sh %s'
export LESS=' -R '

# Aliases
alias exit='confirm && exit'

alias gvim='open -a MacVim'

alias l='ls'
alias la='ls -a'
alias lah='ls -lah | more'
alias lh='ls -lh | more'
alias lha='ls -lah | more'
alias ll='ls -l'
alias lla='ls -la'
alias lm='ls -l | more'

alias lsc='lcd'
alias cls='cdl'

alias launch='open'

alias mvim='open -a MacVim'

alias phpstorm='open -a PhpStorm'

if [ -f ~/.gnupg/.gpg-agent-info ] && [ -n "$(pgrep gpg-agent)" ]; then
		source ~/.gnupg/.gpg-agent-info
		export GPG_AGENT_INFO
else
		eval $(gpg-agent --daemon --write-env-file ~/.gnupg/.gpg-agent-info)
fi

if [ -f $(brew --prefix)/etc/bash_completion ]; then
		. $(brew --prefix)/etc/bash_completion
fi

# Fuck
eval "$(thefuck --alias)"

. ~/profiles/_master
